import type { NextPage } from 'next';
import Head from 'next/head';
import LoadingSpinner from '../components/LoadingSpinner';

const Checkout: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Checkout | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/images/favicon-32x32.png" />
      </Head>

      <main className="flex items-center justify-center min-h-screen">
        <button
          type="button"
          className="flex items-center justify-center bg-app-primary-orange text-white rounded-lg p-4 animate-bounce"
          disabled
        >
          <LoadingSpinner />
          Checkout...
        </button>
      </main>
    </div>
  );
};

export default Checkout;
