import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>Page header</header>

      <main>
        <h1 className="text-xl">Hello, world</h1>
      </main>

      <footer>Page footer</footer>
    </div>
  );
};

export default Home;
